#cloud-config
yum_repos:
    epel-testing:
        baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/$basearch/
        enabled: true
        failovermethod: priority
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        name: EPEL ($basearch)

packages:
  - httpd
  - git
  - oracle-instantclient-release-el8
  - oracle-instantclient-basic
  - [nodejs, 16]

runcmd:
  # Instala a api
  - [git, -C, /home/opc, clone, https://github.com/tiagolpadua/doguito-api.git]
  - [bash, -c, 'cd /home/opc/doguito-api && npm install']

  - [wget, https://objectstorage.us-phoenix-1.oraclecloud.com/n/axnv3l8jdswe/b/site/o/Wallet_doguitodb.zip, -P, /usr/lib/oracle/21/client64/lib/network/admin/]
  - [sudo, sh, -c, 'cd /usr/lib/oracle/21/client64/lib/network/admin/ && unzip -B Wallet_*.zip']
  
  - [wget, https://objectstorage.us-phoenix-1.oraclecloud.com/n/axnv3l8jdswe/b/site/o/doguito-api.service, -p, /lib/systemd/system]

  - [firewall-offline-cmd, --add-service=http]
  - [firewall-offline-cmd, --add-port=3000]

  - [systemctl, daemon-reload]
  - [systemctl, enable, doguito-api.service ]
  - [systemctl, start, doguito-api.service ]
  - [systemctl, enable, httpd]
  - [systemctl, start, httpd]
  - [systemctl, restart, firewalld]