#cloud-config
yum_repos:
    epel-testing:
        baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/$basearch/
        enabled: true
        failovermethod: priority
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        name: EPEL ($basearch)

packages:
  - httpd
  - git

runcmd:
  # Instala o site
  - [git, -C, /var/www, clone, https://github.com/tiagolpadua/doguito-site.git]
  - [rm, -rf, /var/www/html]
  - [mv, /var/www/doguito-site, /var/www/html]

  - [firewall-offline-cmd, --add-service=http]
  - [firewall-offline-cmd, --add-port=3000]
  - [systemctl, daemon-reload]
  - [systemctl, enable, httpd]
  - [systemctl, start, httpd]
  - [systemctl, restart, firewalld]